# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' file-sort name
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/ki/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install

unsetopt beep
bindkey -v
zstyle :compinstall filename '/home/ki/.zshrc'
autoload -Uz add-zsh-hook vcs_info
setopt prompt_subst
add-zsh-hook precmd vcs_info
zstyle ':vcs_info:git:*' formats '%b'

PROMPT='%F{green}%T %F{blue} %~ %F{yellow}${vcs_info_msg_0_}%f
%F{white}> '
export TERM=xterm-256color

export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export CC=/usr/bin/gcc
export GCC=/usr/bin/gcc
export PATH=$HOME/go/bin:$PATH
export XDG_RUNTIME_DIR=/run/user/$(id -u)
source "$HOME/.cargo/env"

export NEOVIDE_MULTIGRID=true
export NEOVIDE_APP_ID=13209

# Modern Unix
alias cat=bat
alias ls="lsd -l"
alias du=dust

# Cargo aliases
alias ch="cargo check"
alias cb="cargo build"
alias cr="cargo run"
alias cu="cargo update"

# C/C++
export CMAKE_CXX_STANDARD=20
export CXX_STANDARD=20

# Wayland
export QT_QPA_PLATFORM=wayland
export MOZ_ENABLE_WAYLAND=1 
export PIPEWIRE_LATENCY="384/48000" 
export PIPEWIRE_LINK_PASSIVE=1 firefox
